# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='user_posted',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
    ]
