# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_jobs_user_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='jobs',
            name='users',
            field=models.ManyToManyField(related_name='jobs', to='users_app.User'),
        ),
    ]
