# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20190325_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theJob', models.CharField(max_length=255)),
                ('theLocation', models.TextField()),
                ('theDescription', models.TextField()),
                ('theUser_posted', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personals', to='users_app.User')),
            ],
        ),
    ]
